### ISSUE TITLE
youtube videos don't load

### ISSUE THREAD

**Issue by agilebean** [Affectiva/youtube-demo#1]
Clicking the "Start" button after entering into field "Enter a URL or search Youtube video" doesn't trigger anything...
It doesn't work either if installed locally.
(
related: 
clicking the youtube videos doesn't work either. 
same behavior on Chrome and Opera, on macOS Sierra
)
A pity- this would be great to demo emotional recognition to colleagues...
Please fix this - thank you!

**Comment by umangmehta12** [comment]
@agilebean : The demo (https://affectiva.github.io/youtube-demo/) works for me on Chrome : Version 58.0.3029.110 and Firefox : version 51.0.1 . The current demo is not supported for Safari. I have updated the supported browsers section in README (https://github.com/Affectiva/youtube-demo#supported-browsers). Can you post the error or the stack trace in the console?

**Comment by agilebean** [comment]
@umangmehta12: thanks a lot for your quick reply.
I just tested again, on both Opera and Chrome (not on Safari).

Here's what I did:
{
python -m SimpleHTTPServer 8000
Opera > http://localhost:8000/
... wait for the webcam to load... (message: "Loading and starting the emotions detector, this may take few minutes ...")
Enter URL into search field: "https://www.youtube.com/watch?v=nVRco_eLjdc"
Click "Start" button
}

On Opera, no stack trace.
On Chrome, I get this:

127.0.0.1 - - [11/Jun/2017 13:34:35] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [11/Jun/2017 13:35:40] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [11/Jun/2017 13:35:41] "GET /demo/css/bootstrap-darkly.min.css HTTP/1.1" 200 -
127.0.0.1 - - [11/Jun/2017 13:35:41] "GET /demo/css/demo.css HTTP/1.1" 200 -
127.0.0.1 - - [11/Jun/2017 13:35:41] "GET /demo/js/vendor/jquery-2.1.4.js HTTP/1.1" 200 -
127.0.0.1 - - [11/Jun/2017 13:35:41] "GET /demo/js/vendor/d3.min.js HTTP/1.1" 200 -
127.0.0.1 - - [11/Jun/2017 13:35:41] "GET /demo/js/run_demo.js HTTP/1.1" 200 -
127.0.0.1 - - [11/Jun/2017 13:35:43] "GET /demo/css/lato.css HTTP/1.1" 200 -
127.0.0.1 - - [11/Jun/2017 13:35:45] "GET /demo/css/lato//MDadn8DQ_3oT6kvnUq_2r_esZW2xOQ-xsNqO47m55DA.woff2 HTTP/1.1" 200 -
127.0.0.1 - - [11/Jun/2017 13:36:09] "GET /demo/css/lato//MgNNr5y1C_tIEuLEmicLmwLUuEpTyoUstqEm5AMlJo4.woff2 HTTP/1.1" 200 -


^C----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 57406)
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/BaseHTTPServer.py", line 310, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
KeyboardInterrupt
----------------------------------------

**Comment by umangmehta12** [comment]
@agilebean I ran the same demo on my python simplehttpserver I was able to load the same video and extract emotional analysis on it. I think you are having issues downloading the dependencies which the affdex.js script pulls down. Seems like your firewall is blocking those incoming files. If you are using mac can you try to use Apache instead (http://osxdaily.com/2012/09/02/start-apache-web-server-mac-os-x/)?

**Comment by agilebean** [comment]
@umangmehta12 moving to apache didn't work, but when I reverted by clearing the hosts file, I started simplehttpserver again and - it worked! i don't know why but i works fine. thanks for your support!
