### ISSUE TITLE
Browser is getting stuck after a while

### ISSUE THREAD

**Issue by shyamchandranmec** [Affectiva/youtube-demo#2]
I am using chrome Version 59.0.3071.115 (Official Build) (64-bit) in Mac OS 10.12.5 (16F73).
After 30 mins the system becomes too slow. In some systems it threw memory exception.
Is there any fix for this?

**Comment by umangmehta12** [comment]
Currently, we haven't released a fix for that. You can bypass it by resetting the detector after like a set threshold or not process a frame when you didn't find a face.

**Comment by shyamchandranmec** [comment]
@umangmehta12  Can you give a sample code for both these solutions.

**Comment by umangmehta12** [comment]
I think you can refer the [documentation](https://knowledge.affectiva.com/docs/analyze-a-video-frame-stream-4) for `onReset()`. The second scenario is already handled by the demo which you can find [here](https://github.com/Affectiva/youtube-demo/blob/gh-pages/demo/js/run_demo.js#L83)

**Comment by shyamchandranmec** [comment]
@umangmehta12  Thanks

**Comment by shyamchandranmec** [comment]
@umangmehta12  I tried calling detector.reset()  after every second but still it hangs after sometime.
